fasta:
  none
long_reads:
  none
short_reads_1:
  none
short_reads_2:
  none
max_threads:
  8
gtdbtk_folder:
    /srv/db/gtdbtk/official/release89
busco_folder:
    /srv/longreads/nanopore/busco
