%YAML 1.1
---
fasta: none
long_reads: none
long_read_type: ont
short_reads_1: none
short_reads_2: none
min_contig_size: 1500
min_bin_size: 200000
max_threads: 8
pplacer_threads: 8
max_memory: 250
genome_size: 5000000
meta_genome_size: 50000000
reference_filter: none
strain_analysis: false
unassembled_long: none
mags: none
mag_directory: none
mag_extension: none
instrain_params: {}
profile_read_list: none
min_long_read_length: 1000
keep_percent: 99
min_mean_q: 80
guppy_model: r941_min_high_g360
gtdbtk_folder: /work/microbiome/db/gtdb/gtdb_release202/auxillary_files/release202
busco_folder: /work/microbiome/db/busco
enrichm_folder: none
virsorter_data: /work/microbiome/db/virsorter_data_v2/virsorter-data
email: somename@email.co
previous_runs: none
min_completeness: none
max_contamination: none
ani: none
precluster_ani: none
precluster_method: none
