%YAML 1.1
---
fasta: none
long_reads: none
long_read_type: ont
short_reads_1: none
short_reads_2: none
min_contig_size: 1500
min_bin_size: 200000
max_threads: 8
pplacer_threads: 8
max_memory: 250
genome_size: 5000000
reference_filter: none
strain_analysis: false
unassembled_long: none
mags: none
mag_directory: none
mag_extension: none
instrain_params: {}
profile_read_list: none
min_long_read_length: 500
keep_percent: 99
min_mean_q: 40
guppy_model: r941_min_high_g360
gtdbtk_folder: /bio_data/gtdbtk/release202/
busco_folder: none
checkm2_db_folder: ~/databases/CheckM2_database/
eggnog_folder: /bio_data/emapper/
virsorter_data: none
email: somename@email.co
gsa:
- /home/rhys_newell_microba_com/git/aviary/none
gsa_mappings: none
semibin_model: global
kmer_sizes:
- auto
use_megahit: false
coassemble: true
min_cov_long: 20
min_cov_short: 3
exclude_contig_cov: 100
exclude_contig_size: 25000
long_contig_size: 100000
use_checkm2_scores: false
previous_runs: none
min_completeness: none
max_contamination: none
ani: none
precluster_ani: none
precluster_method: none
pggb_params: none
tmpdir: /tmp
