fasta:
  none
long_reads:
  none
short_reads_1:
  none
short_reads_2:
  none
batch_file:
  none
max_threads:
  8
virsorter_data:
  /srv/db/virsorter_data_v2/virsorter-data
gtdbtk_folder:
  /srv/db/gtdbtk/official/release95
busco_folder:
  /srv/longreads/nanopore/busco
binsnek_install:
  ~/git/BinSnek/