fasta:
    none
long_reads:
    none
long_read_type:
    ont
short_reads_1:
    none
short_reads_2:
    none
min_contig_size:
    1500
min_bin_size:
    200000
max_threads:
    8
pplacer_threads:
    8
max_memory:
    250
genome_size:
    5000000
meta_genome_size:
    50000000
reference_filter:
    none
strain_analysis:
    False
unassembled_long:
    none
instrain_params:
    {}
profile_read_list:
    none
guppy_model:
    r941_min_high_g360
gtdbtk_folder:
    /work/microbiome/db/gtdbtk/release95/
busco_folder:
    /work/microbiome/db/busco
virsorter_data:
    /work/microbiome/db/virsorter_data_v2/virsorter-data
email:
    somename@email.co