fasta:
  none
long_reads:
  none
long_read_type:
  nanopore
short_reads_1:
  none
short_reads_2:
  none
min_contig_size:
  1500
min_bin_size:
  200000
max_threads:
  8
pplacer_threads:
  8
virsorter_data:
  /work/microbiome/db/virsorter_data_v2/virsorter-data
gtdbtk_folder:
  /work/microbiome/db/gtdbtk/release95/
busco_folder:
  /work/microbiome/db/busco
